### ISSUE TITLE
Site appears in Publisher section but unable to publish to it or the publish queue?

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [superdesk/superdesk#2907]
The site can be seen at:

http://18.217.179.45/

In Superdesk it correctly appears in the publisher section, with all the routing correctly setup to the example.

Although the site is full of the example content, when I go to the publisher section I just initially had two example articles in the incoming section. None of the articles on the site appear in published.

![screenshot from 2018-06-11 12-03-54](https://user-images.githubusercontent.com/38424470/41228263-aa9402ca-6d6f-11e8-96be-5c0fbc21a40a.png)
(the one is in published to web because I published it, which worked).

When I go to an article that I've wrote and click the publish button it says that "No websites have been set".

![screenshot from 2018-06-11 12-07-26](https://user-images.githubusercontent.com/38424470/41228452-514805c6-6d70-11e8-89eb-01a07326e463.png)

If I publish it anyway it doesn't appear in the incoming list in the output control in publisher. Neither does it appear in the publish queue section of Superdesk.

I've checked both the Superdesk and server logs and there's no errors in there at all.

**Comment by petrjasek** [comment]
ping @superdesk/superdesk-publishing

**Comment by ahilles107** [comment]
if it's not in publishing queue then it wasnt pushed to subscriber. Can You show us your subscriber config?

**Comment by CaerphillyMediaLtd** [comment]
Maybe I have it setup wrong? I couldn't find very good documentation on how to setup the subscriber.

![screenshot from 2018-06-11 14-46-14](https://user-images.githubusercontent.com/38424470/41235330-7f0735c0-6d86-11e8-9adb-749e4011c722.png)
![screenshot from 2018-06-11 14-46-27](https://user-images.githubusercontent.com/38424470/41235331-7f1fb924-6d86-11e8-80e2-26ee8f77f30b.png)

**Comment by ahilles107** [comment]
Imo - product is missing. Please create one in superdesk setting, choose product type: both, and attach it to your subscriber. Products are used for routing articles to subscribers.

**Comment by CaerphillyMediaLtd** [comment]
Thank you that works, it now appears in the queue.

Maybe I've done it wrong again, but now in the queue I get a 401 error?

PublishHTTPPushClientError Error 14001 - HTTP push publish client error:Error pushing item 401: Bad credentials

**Comment by ahilles107** [comment]
If You provided secret key in organization (when created) then it must be provided in subscriber settings. Superdesk had a bug (fixed in one of latest commits) related to it. So my advice for now is to set secret code in database (tabe swp_organization) to `null`.

**Comment by CaerphillyMediaLtd** [comment]
Thank you, I've done that and it works now.

I did encounter a bug just then though, even though I changed the key in the settings menu on the old subscriber it still kept sending the previous one. I had to create a new subscriber and use that (that one does update correctly though).

**Comment by CaerphillyMediaLtd** [comment]
This works fine for text articles but for all images I still get a bad credentials error?

**Comment by ahilles107** [comment]
And you have secret set to `null` now? As issue with assets and secret provided was fixed in latest sd master (but not released yet in publisher branch).

**Comment by ahilles107** [comment]
We are in process of stabilisation for 1.4 release. After release it will work with security keys, and latest superdesk.
